clear;

drop table TMP_MEDICAMENTO;

create table TMP_MEDICAMENTO
(
  NOME_PRODUTO VARCHAR2(4000),
  NOME_FABRICANTE  VARCHAR2(4000),
  NOME_FAMILIA     VARCHAR2(4000)
);

prompt Deleting TMP_MEDICAMENTO...
delete from TMP_MEDICAMENTO;
prompt Loading TMP_MEDICAMENTO...
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('AMOXI-PED', 'STIEFEL', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('AMOXICILINA', 'SANDOZ', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('AMOXICILINA+CLAVULANATO DE POTASSIO', 'SANDOZ', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('AZITRAX', 'FARMOQUIMICA', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('AZITROMICINA', 'MEDLEY', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CELEXIN', 'MANTECORP', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CETONAX', 'JANSSEN-CILAG', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORCIN', 'STIEFEL', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE CIPROFLOXACINO', 'BIOSINTETICA FARMA', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FLUCONAZOL', 'BIOSINTETICA FARMA', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LAMISIL', 'NOVARTIS BIOCIENCI', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LEVAQUIN', 'JANSSEN-CILAG', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NIZORAL', 'JANSSEN-CILAG', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SPORANOX', 'JANSSEN-CILAG', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('UNIZOL', 'FARMOQUIMICA', 'ANTIINFECCIOSOS EM GERAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('AXID', 'FARMOQUIMICA', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('AZUKON', 'TORRENT', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('AZULIX', 'TORRENT', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('BROMOPRIDA', 'BIOSINTETICA FARMA', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CALCI-PED', 'STIEFEL', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CALCIUM D3', 'NOVARTIS BIOCIENCI', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE METFORMINA', 'BIOSINTETICA FARMA', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE SIBUTRAMINA', 'SANDOZ', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('COENAPLEX', 'LILLY', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DICETEL', 'ALTANA', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DIMEFOR', 'FARMOQUIMICA', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DIMETICONA', 'MEDLEY', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DOMPERIDONA', 'MEDLEY', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('GLIBENCLAMIDA', 'BIOSINTETICA FARMA', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('GLIMEPIL', 'FARMOQUIMICA', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('GLIMEPIRIDA', 'BIOSINTETICA FARMA', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('GLIMEPIRIDA', 'MEDLEY', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('HUMULIN', 'LILLY', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MATERNA', 'WYETH', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MATERVIT', 'FARMOQUIMICA', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MOTILIUM', 'JANSSEN-CILAG', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MYLICON', 'JANSSEN-CILAG', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PANTOZOL', 'ALTANA', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PARIET', 'JANSSEN-CILAG', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SLOW K', 'NOVARTIS BIOCIENCI', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('STARFORM', 'NOVARTIS BIOCIENCI', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('STARLIX', 'NOVARTIS BIOCIENCI', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('VITA-PED', 'STIEFEL', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ZELMAC', 'NOVARTIS BIOCIENCI', 'APARELHO DIGESTIVO E METABOLISMO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ABRILAR', 'FARMOQUIMICA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ACEBROFILINA', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ALENIA', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ALERGO FILINAL', 'EUROFARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ATROVENT', 'BOEHRINGER', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('BROMETO DE IPATROPIO', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('BUSONID', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CARBOCISTEINA', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE AMBROXOL', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('COMBIVENT', 'BOEHRINGER', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DICLORIDRATO DE CETIRIZINA', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FLUIR', 'MANTECORP', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FLUTICAPS', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FORADIL', 'NOVARTIS BIOCIENCI', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FORASEQ', 'NOVARTIS BIOCIENCI', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FORMOCAPS', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FUMARATO DE CETOTIFENO', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FUMARATO DE CETOTIFENO', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LORATADINA', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LORATADINA+PSEUDOEFEDRINA', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('POLARAMINE', 'MANTECORP', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('RUPAFIN', 'BIOSINTETICA FARMA', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SPIRIVA', 'BOEHRINGER', 'APARELHO RESPIRATÓRIO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ACNESOAP', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ADAPALENO', 'BIOSINTETICA FARMA', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('BABIX', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('BETADERM', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('BETADERM N', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CETONAX', 'JANSSEN-CILAG', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLARIPEL', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLINAGEL', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DALAP', 'BIOSINTETICA FARMA', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DIPROGENTA', 'MANTECORP', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DIPROSALIC', 'MANTECORP', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DIPROSONE', 'MANTECORP', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DUOFILM', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ELIDEL', 'NOVARTIS BIOCIENCI', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('EPIDRAT', 'MANTECORP', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('EPISOL', 'MANTECORP', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FINASTERIDA', 'BIOSINTETICA FARMA', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FUROATO DE MOMETASONA', 'BIOSINTETICA FARMA', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FUROATO DE MOMETASONA', 'MEDLEY', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('HIDRAFIL', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('HIDRAPEL', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ISOTREX', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ISOTREXOL', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LACTICARE', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LAMISIL', 'NOVARTIS BIOCIENCI', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MICETAL', 'BIOSINTETICA FARMA', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NIZORAL', 'JANSSEN-CILAG', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('POLARAMINE', 'MANTECORP', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PRURIX', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('QUADRIDERM', 'MANTECORP', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SASTID', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SOLUGEL', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SPECTRABAN', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('STIEFCORTIL', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('STIEFDERM', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('STIEMYCIN', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TARFLEX', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TRIANCINOLONA+GRAMICIDINA+NEOMICINA+NISTATINA', 'MEDLEY', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('VAL BETAMETASONA+GENTAMICINA+TOLNAFTATO+CLIOQ', 'MEDLEY', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('VITANOL-A', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('WARTEC', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ZN SHAMPOO', 'STIEFEL', 'DERMATOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MEBENDAZOL', 'MEDLEY', 'PARASITOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PANTELMIN', 'JANSSEN-CILAG', 'PARASITOLOGIA');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CELESTAMINE', 'MANTECORP', 'PREPARADOS HORMONAIS (EXCLUINDO HORMÔNIOS SEXUAIS)');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CELESTONE', 'MANTECORP', 'PREPARADOS HORMONAIS (EXCLUINDO HORMÔNIOS SEXUAIS)');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DIPROSPAN', 'MANTECORP', 'PREPARADOS HORMONAIS (EXCLUINDO HORMÔNIOS SEXUAIS)');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PREDSIM', 'MANTECORP', 'PREPARADOS HORMONAIS (EXCLUINDO HORMÔNIOS SEXUAIS)');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DISGREN', 'BIOSINTETICA FARMA', 'SANGUE E ÓRGAOS FORMADORES DE SANGUE');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NORIPURUM', 'ALTANA', 'SANGUE E ÓRGAOS FORMADORES DE SANGUE');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NORIPURUM FOLICO', 'ALTANA', 'SANGUE E ÓRGAOS FORMADORES DE SANGUE');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NORIPURUM VITAMINADO', 'ALTANA', 'SANGUE E ÓRGAOS FORMADORES DE SANGUE');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PREMARIN', 'WYETH', 'SANGUE E ÓRGAOS FORMADORES DE SANGUE');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('VASOGARD', 'BIOSINTETICA FARMA', 'SANGUE E ÓRGAOS FORMADORES DE SANGUE');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('AMLOCOR', 'TORRENT', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ANGIPRESS', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ANGIPRESS CD', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ATENOLOL+CLORTALIDONA', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('BESILATO DE ANLODIPINO', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('BETACARD', 'TORRENT', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CAPTOPRIL+HIDROCLOROTIAZIDA', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CARDIZEM', 'BOEHRINGER', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CARVEDILOL', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE AMILORIDA+HIDROCLOROTIAZIDA', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE AMIODARONA', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE DILTIAZEM', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE SOTALOL', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CORDARENE', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CORDAREX', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CORUS', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CORUS H', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DILTOR', 'TORRENT', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DIOCOMB', 'NOVARTIS BIOCIENCI', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DIOVAN', 'NOVARTIS BIOCIENCI', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DIOVAN AMLO', 'NOVARTIS BIOCIENCI', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DIOVAN HCT', 'NOVARTIS BIOCIENCI', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ECATOR', 'TORRENT', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ECATOR H', 'TORRENT', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('EUPRESSIN', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('EUPRESSIN H', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FUROSEMIDA', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('GENFIBROZILA', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('INDAPEN', 'TORRENT', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('KARVIL', 'TORRENT', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LESCOL', 'NOVARTIS BIOCIENCI', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LISINOPRIL', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LISINOPRIL+HIDROCLOROTIAZIDA', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LISTRIL', 'TORRENT', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LOSARTANA POTASSICA', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LOTAR', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MALEATO DE ENALAPRIL', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MALEATO DE ENALAPRIL+HIDROCLOROTIAZIDA', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('METILDOPA', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MICARDIS', 'BOEHRINGER', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MICARDIS HCT', 'BOEHRINGER', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MINOR', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MIODARON', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MONONITRATO DE ISOSSORBIDA', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NIFELAT', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NITRENCORD', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NITRENDIPINO', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('OXCORD', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('OXIGEN', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PENTOXIFILINA', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('RAMIPRIL', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SINERGEN', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('STUGERON', 'JANSSEN-CILAG', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TARTARATO DE METROPOLOL', 'BIOSINTETICA FARMA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TEBONIN', 'ALTANA', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TORLOS', 'TORRENT', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TORLOS H', 'TORRENT', 'SISTEMA CARDIOVASCULAR');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ACETATO DE CLOSTEBOL+SULF.NEOMICINA', 'MEDLEY', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ADOLESS', 'FARMOQUIMICA', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CERAZETTE', 'ORGANON', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CIALIS', 'LILLY', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLIMADERM', 'WYETH', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('COLPISTAR', 'FARMOQUIMICA', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ESTALIS', 'NOVARTIS BIOCIENCI', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ESTRADOT', 'NOVARTIS BIOCIENCI', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('EVANOR', 'WYETH', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('EVISTA', 'LILLY', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('EVRA', 'JANSSEN-CILAG', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FINASTERIDA', 'BIOSINTETICA FARMA', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('GINESSE', 'FARMOQUIMICA', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('GRACIAL', 'ORGANON', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('GYNOMAX', 'FARMOQUIMICA', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('HARMONET', 'WYETH', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LIVIAL', 'ORGANON', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LOMEXIN', 'ALTANA', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MACRODANTINA', 'MANTECORP', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MERCILON', 'ORGANON', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MINESSE', 'WYETH', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MINULET', 'WYETH', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NORDETTE', 'WYETH', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NORTREL', 'WYETH', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NUVARING', 'ORGANON', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('POSTOVAL', 'WYETH', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PREFEST', 'JANSSEN-CILAG', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PREMARIN', 'WYETH', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PREMELLE', 'WYETH', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('REDUCLIM', 'FARMOQUIMICA', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SECNI-PLUS', 'FARMOQUIMICA', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SECOTEX', 'BOEHRINGER', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SYSTEN', 'JANSSEN-CILAG', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SYSTEN CONTI', 'JANSSEN-CILAG', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SYSTEN SEQUI', 'JANSSEN-CILAG', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TOTELLE', 'WYETH', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TRINORDIOL', 'WYETH', 'SISTEMA GENITURINÁRIO E HORMÔNIOS SEXUAIS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ALENDIL', 'FARMOQUIMICA', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ALENDRONATO SODICO', 'BIOSINTETICA FARMA', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CATAFLAM', 'NOVARTIS BIOCIENCI', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DICLOFENACO DE POTASSIO', 'BIOSINTETICA FARMA', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DICLOFENACO RESINATO', 'BIOSINTETICA FARMA', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('FLOTAC', 'NOVARTIS BIOCIENCI', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('INICOX', 'FARMOQUIMICA', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MELOXICAM', 'BIOSINTETICA FARMA', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MOVATEC', 'BOEHRINGER', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NAPROXENO', 'BIOSINTETICA FARMA', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PARALON', 'JANSSEN-CILAG', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PREXIGE', 'NOVARTIS BIOCIENCI', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SCAFLAM', 'MANTECORP', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TENOXEN', 'BIOSINTETICA FARMA', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('VOLTAREN', 'NOVARTIS BIOCIENCI', 'SISTEMA MUSCULO ESQUELÉTICO');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ACIDO MEFENÂMICO', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ALCYTAM', 'TORRENT', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ALIVIUM', 'MANTECORP', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ALPRAZOLAM', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ALTROX', 'TORRENT', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('APRAZ', 'MANTECORP', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ARTANE', 'WYETH', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('BROMAZEPAM', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CARBAMAZEPINA', 'MEDLEY', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CARBIDOPA+LEVODOPA', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CITALOPRAM', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CITALOPRAM', 'SANDOZ', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLONAZEPAM', 'MEDLEY', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLONOTRIL', 'TORRENT', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE PAROXETINA', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE SELEGILINA', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE SERTRALINA', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE SERTRALINA', 'MEDLEY', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CONCERTA', 'JANSSEN-CILAG', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CYMBALTA', 'LILLY', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DEPRILAN', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DERMOMAX', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DIPIRONA SODICA', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DOLAMIN', 'FARMOQUIMICA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('DUODOPA', 'TORRENT', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('EFEXOR', 'WYETH', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ERANZ', 'WYETH', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('EXELON', 'NOVARTIS BIOCIENCI', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('GABAPENTINA', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('JARSIN', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LAMITOR', 'TORRENT', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LIORAM', 'MANTECORP', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('LORAX', 'WYETH', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('OLCADIL', 'NOVARTIS BIOCIENCI', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PAMELOR', 'NOVARTIS BIOCIENCI', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PARACETAMOL', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PARACETAMOL', 'SANDOZ', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PROMETAX', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('PROZAC', 'LILLY', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('REMERON', 'ORGANON', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('REMINYL', 'JANSSEN-CILAG', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('RESPIDON', 'TORRENT', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('RISPERDAL', 'JANSSEN-CILAG', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('SERENATA', 'TORRENT', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TACRINAL', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TOLREST', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TOPAMAX', 'JANSSEN-CILAG', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TOPIRAMATO', 'SANDOZ', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TORVAL', 'TORRENT', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TRILEPTAL', 'NOVARTIS BIOCIENCI', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ULTRACET', 'JANSSEN-CILAG', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('VENLIFT', 'TORRENT', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ZARGUS', 'BIOSINTETICA FARMA', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ZYPREXA', 'LILLY', 'SISTEMA NERVOSO CENTRAL');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CETOROLACO DE TROMETAMINA', 'BIOSINTETICA FARMA', 'ÓRGÃOS DOS SENTIDOS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('CLORIDRATO DE DORZOLAMIDA', 'BIOSINTETICA FARMA', 'ÓRGÃOS DOS SENTIDOS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('GARASONE', 'MANTECORP', 'ÓRGÃOS DOS SENTIDOS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('HYPOTEARS', 'NOVARTIS BIOCIENCI', 'ÓRGÃOS DOS SENTIDOS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('MALEATO DE TIMOLOL', 'BIOSINTETICA FARMA', 'ÓRGÃOS DOS SENTIDOS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('NYOLOL', 'NOVARTIS BIOCIENCI', 'ÓRGÃOS DOS SENTIDOS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TOBRAMICINA', 'BIOSINTETICA FARMA', 'ÓRGÃOS DOS SENTIDOS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('TOBRAMICINA+DEXAMETASONA', 'BIOSINTETICA FARMA', 'ÓRGÃOS DOS SENTIDOS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('VISCOTEARS', 'NOVARTIS BIOCIENCI', 'ÓRGÃOS DOS SENTIDOS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('VOLTAREN', 'NOVARTIS BIOCIENCI', 'ÓRGÃOS DOS SENTIDOS');
insert into TMP_MEDICAMENTO (NOME_PRODUTO, NOME_FABRICANTE, NOME_FAMILIA)
values ('ZADITEN COLIRIO', 'NOVARTIS BIOCIENCI', 'ÓRGÃOS DOS SENTIDOS');
commit;

delete from produto;
commit;

delete from familia;
commit;

delete from fabricante;
commit;

declare

  cursor c_medicamento
  is
    select
      nome_produto,
      nome_fabricante,
      nome_familia
    from
      tmp_medicamento;

  cursor c_familia
  (
    p_nome in familia.nome%type
  )
  is
    select
      id
    from
      familia
    where
      nome = p_nome;

  cursor c_fabricante
  (
    p_nome in fabricante.nome%type
  )
  is
    select
      id
    from
      fabricante
    where
      nome = p_nome;
      
  cursor c_produto
  (
    p_nome          in produto.nome%type,
    p_id_familia    in produto.id_familia%type,
    p_id_fabricante in produto.id_fabricante%type
  )
  is
    select
      id
    from
      produto
    where
      nome = p_nome and
      id_familia = p_id_familia and
      id_fabricante = p_id_fabricante;

  r_medicamento    c_medicamento%rowtype; 
  r_familia        c_familia%rowtype;
  r_fabricante     c_fabricante%rowtype;     
  r_produto        c_produto%rowtype;

  v_id_familia     produto.id_familia%type;
  v_id_fabricante  produto.id_fabricante%type;
  v_id_produto     produto.id%type;

begin

  open c_medicamento;
  
  loop
  
    fetch c_medicamento into r_medicamento;
    
    exit when c_medicamento%notfound;
    
    open c_familia(r_medicamento.nome_familia);

    fetch c_familia into r_familia;

    if c_familia%notfound then
    
      select
        nvl(max(id), 0) + 1
      into
        v_id_familia
      from
        familia;
    
      insert into familia
      (
        id,
        codigo,
        nome
      )
      values
      (
        v_id_familia,
        to_char(v_id_familia, '00'),
        r_medicamento.nome_familia
      );
    
    else
    
      v_id_familia := r_familia.id;
    
    end if;

    close c_familia;

    open c_fabricante(r_medicamento.nome_fabricante);

    fetch c_fabricante into r_fabricante;

    if c_fabricante%notfound then
    
      select
        nvl(max(id), 0) + 1
      into
        v_id_fabricante
      from
        fabricante;

      insert into fabricante
      (
        id,
        codigo,
        nome
      )
      values
      (
        v_id_fabricante,
        to_char(v_id_fabricante, '000'),
        r_medicamento.nome_fabricante
      );
    
    else
    
      v_id_fabricante := r_fabricante.id;
    
    end if;

    close c_fabricante;

    open c_produto(r_medicamento.nome_produto, v_id_familia, v_id_fabricante);

    fetch c_produto into r_produto;

    if c_produto%notfound then
    
      select
        nvl(max(id), 0) + 1
      into
        v_id_produto
      from
        produto;
    
      insert into produto
      (
        id,
        codigo,
        nome,
        id_familia,
        id_fabricante
      )
      values
      (
        v_id_produto,
        to_char(v_id_produto, '0000'),
        r_medicamento.nome_produto,
        v_id_familia,
        v_id_fabricante
      );
    
    end if;

    close c_produto;
  
  end loop;
  
  close c_medicamento;

end;
/

commit;

drop table TMP_MEDICAMENTO;

select * from familia order by id;

select * from fabricante order by id;

select * from produto order by id;

