DELETE FROM NOTIFICACAO;
COMMIT;

EXEC PKG_NOTIFICACAO.NOTIFICA_LINHA('ETL_OLTP', 'CIDADE', NULL);
EXEC PKG_NOTIFICACAO.NOTIFICA_LINHA('ETL_OLTP', 'CLIENTE', NULL);
EXEC PKG_NOTIFICACAO.NOTIFICA_LINHA('ETL_OLTP', 'FAMILIA', NULL);
EXEC PKG_NOTIFICACAO.NOTIFICA_LINHA('ETL_OLTP', 'PEDIDO_VENDA', NULL);
EXEC PKG_NOTIFICACAO.NOTIFICA_LINHA('ETL_OLTP', 'PRODUTO', NULL);
EXEC PKG_NOTIFICACAO.NOTIFICA_LINHA('ETL_OLTP', 'REPRESENTANTE', NULL);

COMMIT;
