delete from pais;
insert into pais values (seq_pais.nextval,'AD','Andorra');
insert into pais values (seq_pais.nextval,'AE','Emirados Arabes Unidos');
insert into pais values (seq_pais.nextval,'AF','Afeganistao');
insert into pais values (seq_pais.nextval,'AG','Antigua e Barbuda');
insert into pais values (seq_pais.nextval,'AI','Anguilha');
insert into pais values (seq_pais.nextval,'AL','Albania');
insert into pais values (seq_pais.nextval,'AM','Armenia');
insert into pais values (seq_pais.nextval,'AN','Antilhas Holandesas');
insert into pais values (seq_pais.nextval,'AO','Angola');
insert into pais values (seq_pais.nextval,'AR','Argentina');
insert into pais values (seq_pais.nextval,'AS','Samoa Americana');
insert into pais values (seq_pais.nextval,'AT','Austria');
insert into pais values (seq_pais.nextval,'AU','Australia');
insert into pais values (seq_pais.nextval,'AW','Aruba');
insert into pais values (seq_pais.nextval,'AZ','Azerbaijao');
insert into pais values (seq_pais.nextval,'BA','Bosnia e Herzegovina');
insert into pais values (seq_pais.nextval,'BB','Barbados');
insert into pais values (seq_pais.nextval,'BD','Bangladesh');
insert into pais values (seq_pais.nextval,'BE','Belgica');
insert into pais values (seq_pais.nextval,'BF','Burquina Faso');
insert into pais values (seq_pais.nextval,'BG','Bulgaria');
insert into pais values (seq_pais.nextval,'BH','Barem');
insert into pais values (seq_pais.nextval,'BI','Burundi');
insert into pais values (seq_pais.nextval,'BJ','Benim');
insert into pais values (seq_pais.nextval,'BM','Bermudas');
insert into pais values (seq_pais.nextval,'BN','Brunei');
insert into pais values (seq_pais.nextval,'BO','Bolivia');
insert into pais values (seq_pais.nextval,'BR','Brasil');
insert into pais values (seq_pais.nextval,'BS','Bahamas');
insert into pais values (seq_pais.nextval,'BT','Butao');
insert into pais values (seq_pais.nextval,'BU','Burma');
insert into pais values (seq_pais.nextval,'BW','Botsuana');
insert into pais values (seq_pais.nextval,'BY','Bielorrússia');
insert into pais values (seq_pais.nextval,'BZ','Belize');
insert into pais values (seq_pais.nextval,'CA','Canada');
insert into pais values (seq_pais.nextval,'CC','Ilhas dos Cocos');
insert into pais values (seq_pais.nextval,'CD','Republica Democratica do Congo');
insert into pais values (seq_pais.nextval,'CF','Republica Centro-Africana');
insert into pais values (seq_pais.nextval,'CG','Congo');
insert into pais values (seq_pais.nextval,'CH','Suica');
insert into pais values (seq_pais.nextval,'CK','Ilhas Cook');
insert into pais values (seq_pais.nextval,'CL','Chile');
insert into pais values (seq_pais.nextval,'CM','Camaroes');
insert into pais values (seq_pais.nextval,'CN','China');
insert into pais values (seq_pais.nextval,'CO','Colombia');
insert into pais values (seq_pais.nextval,'CR','Costa Rica');
insert into pais values (seq_pais.nextval,'CU','Cuba');
insert into pais values (seq_pais.nextval,'CV','Cabo Verde');
insert into pais values (seq_pais.nextval,'CX','Ilha do Natal');
insert into pais values (seq_pais.nextval,'CY','Chipre');
insert into pais values (seq_pais.nextval,'CZ','Republica Checa');
insert into pais values (seq_pais.nextval,'DE','Alemanha');
insert into pais values (seq_pais.nextval,'DJ','Jibuti');
insert into pais values (seq_pais.nextval,'DK','Dinamarca');
insert into pais values (seq_pais.nextval,'DM','Dominica');
insert into pais values (seq_pais.nextval,'DO','Republica Dominicana');
insert into pais values (seq_pais.nextval,'EC','Equador');
insert into pais values (seq_pais.nextval,'EE','Estonia');
insert into pais values (seq_pais.nextval,'EG','Egito');
insert into pais values (seq_pais.nextval,'EH','Sahara Ocidental');
insert into pais values (seq_pais.nextval,'ES','Espanha');
insert into pais values (seq_pais.nextval,'ET','Etiopia');
insert into pais values (seq_pais.nextval,'FI','Finlandia');
insert into pais values (seq_pais.nextval,'FJ','Fiji');
insert into pais values (seq_pais.nextval,'FK','Ilhas Malvinas');
insert into pais values (seq_pais.nextval,'FM','Micronesia');
insert into pais values (seq_pais.nextval,'FO','Ilhas Faroe');
insert into pais values (seq_pais.nextval,'FR','Franca');
insert into pais values (seq_pais.nextval,'GA','Gabao');
insert into pais values (seq_pais.nextval,'GB','Reino Unido');
insert into pais values (seq_pais.nextval,'GD','Granada');
insert into pais values (seq_pais.nextval,'GE','Georgia');
insert into pais values (seq_pais.nextval,'GF','Guiana Francesa');
insert into pais values (seq_pais.nextval,'GH','Gana');
insert into pais values (seq_pais.nextval,'GI','Gibraltar');
insert into pais values (seq_pais.nextval,'GL','Groenlandia');
insert into pais values (seq_pais.nextval,'GM','Gambia');
insert into pais values (seq_pais.nextval,'GN','Guine');
insert into pais values (seq_pais.nextval,'GP','Guadalupe');
insert into pais values (seq_pais.nextval,'GQ','Guine Equatorial');
insert into pais values (seq_pais.nextval,'GR','Grecia');
insert into pais values (seq_pais.nextval,'GT','Guatemala');
insert into pais values (seq_pais.nextval,'GU','Guame');
insert into pais values (seq_pais.nextval,'GW','Guine-Bissau');
insert into pais values (seq_pais.nextval,'GY','Guiana');
insert into pais values (seq_pais.nextval,'HK','Hong Kong');
insert into pais values (seq_pais.nextval,'HN','Honduras');
insert into pais values (seq_pais.nextval,'HR','Croacia');
insert into pais values (seq_pais.nextval,'HT','Haiti');
insert into pais values (seq_pais.nextval,'HU','Hungria');
insert into pais values (seq_pais.nextval,'ID','Indonesia');
insert into pais values (seq_pais.nextval,'IE','Irlanda');
insert into pais values (seq_pais.nextval,'IL','Israel');
insert into pais values (seq_pais.nextval,'IN','India');
insert into pais values (seq_pais.nextval,'IO','Territorio Britanico do Oceano Indico');
insert into pais values (seq_pais.nextval,'IQ','Iraque');
insert into pais values (seq_pais.nextval,'IR','Ira');
insert into pais values (seq_pais.nextval,'IS','Islandia');
insert into pais values (seq_pais.nextval,'IT','Italia');
insert into pais values (seq_pais.nextval,'JM','Jamaica');
insert into pais values (seq_pais.nextval,'JO','Jordania');
insert into pais values (seq_pais.nextval,'JP','Japao');
insert into pais values (seq_pais.nextval,'KE','Quenia');
insert into pais values (seq_pais.nextval,'KG','Quirguizistao');
insert into pais values (seq_pais.nextval,'KH','Camboja');
insert into pais values (seq_pais.nextval,'KI','Quiribati');
insert into pais values (seq_pais.nextval,'KM','Comores');
insert into pais values (seq_pais.nextval,'KN','Sao Cristovao e Neves');
insert into pais values (seq_pais.nextval,'KP','Coreia do Norte');
insert into pais values (seq_pais.nextval,'KR','Coreia do Sul');
insert into pais values (seq_pais.nextval,'KY','Ilhas Cayman');
insert into pais values (seq_pais.nextval,'KZ','Cazaquistao');
insert into pais values (seq_pais.nextval,'LA','Laos');
insert into pais values (seq_pais.nextval,'LB','Libano');
insert into pais values (seq_pais.nextval,'LC','Santa Lucia');
insert into pais values (seq_pais.nextval,'LI','Listenstaine');
insert into pais values (seq_pais.nextval,'LK','Sri Lanka');
insert into pais values (seq_pais.nextval,'LR','Liberia');
insert into pais values (seq_pais.nextval,'LS','Lesoto');
insert into pais values (seq_pais.nextval,'LT','Lituania');
insert into pais values (seq_pais.nextval,'LU','Luxemburgo');
insert into pais values (seq_pais.nextval,'LY','Libia');
insert into pais values (seq_pais.nextval,'MA','Marrocos');
insert into pais values (seq_pais.nextval,'MC','Monaco');
insert into pais values (seq_pais.nextval,'MD','Moldavia');
insert into pais values (seq_pais.nextval,'MG','Madagascar');
insert into pais values (seq_pais.nextval,'MH','Ilhas Marshall');
insert into pais values (seq_pais.nextval,'MK','Macedonia');
insert into pais values (seq_pais.nextval,'ML','Mali');
insert into pais values (seq_pais.nextval,'MM','Birmania');
insert into pais values (seq_pais.nextval,'MN','Mongolia');
insert into pais values (seq_pais.nextval,'MO','Macau');
insert into pais values (seq_pais.nextval,'MP','Marianas do Norte');
insert into pais values (seq_pais.nextval,'MQ','Martinica');
insert into pais values (seq_pais.nextval,'MR','Mauritania');
insert into pais values (seq_pais.nextval,'MS','Montserrat');
insert into pais values (seq_pais.nextval,'MT','Malta');
insert into pais values (seq_pais.nextval,'MU','Mauricia');
insert into pais values (seq_pais.nextval,'MV','Maldivas');
insert into pais values (seq_pais.nextval,'MW','Malawi');
insert into pais values (seq_pais.nextval,'MX','Mexico');
insert into pais values (seq_pais.nextval,'MY','Malasia');
insert into pais values (seq_pais.nextval,'MZ','Mocambique');
insert into pais values (seq_pais.nextval,'NA','Namibia');
insert into pais values (seq_pais.nextval,'NC','Nova Caledonia');
insert into pais values (seq_pais.nextval,'NE','Niger');
insert into pais values (seq_pais.nextval,'NF','Ilha Norfolk');
insert into pais values (seq_pais.nextval,'NG','Nigeria');
insert into pais values (seq_pais.nextval,'NI','Nicaragua');
insert into pais values (seq_pais.nextval,'NL','Holanda');
insert into pais values (seq_pais.nextval,'NO','Noruega');
insert into pais values (seq_pais.nextval,'NP','Nepal');
insert into pais values (seq_pais.nextval,'NR','Nauru');
insert into pais values (seq_pais.nextval,'NU','Niue');
insert into pais values (seq_pais.nextval,'NZ','Nova Zelandia');
insert into pais values (seq_pais.nextval,'OM','Oma');
insert into pais values (seq_pais.nextval,'PA','Panama');
insert into pais values (seq_pais.nextval,'PE','Peru');
insert into pais values (seq_pais.nextval,'PF','Polinesia Francesa');
insert into pais values (seq_pais.nextval,'PG','Papua-Nova Guine');
insert into pais values (seq_pais.nextval,'PH','Filipinas');
insert into pais values (seq_pais.nextval,'PK','Paquistao');
insert into pais values (seq_pais.nextval,'PL','Polonia');
insert into pais values (seq_pais.nextval,'PM','Sao Pedro e Miquelon');
insert into pais values (seq_pais.nextval,'PN','Pitcairn');
insert into pais values (seq_pais.nextval,'PR','Porto Rico');
insert into pais values (seq_pais.nextval,'PT','Portugal');
insert into pais values (seq_pais.nextval,'PW','Palau');
insert into pais values (seq_pais.nextval,'PY','Paraguai');
insert into pais values (seq_pais.nextval,'QA','Catar');
insert into pais values (seq_pais.nextval,'RE','Reuniao');
insert into pais values (seq_pais.nextval,'RO','Romenia');
insert into pais values (seq_pais.nextval,'RU','Russia');
insert into pais values (seq_pais.nextval,'RW','Ruanda');
insert into pais values (seq_pais.nextval,'RYY','Wallis e Futuna');
insert into pais values (seq_pais.nextval,'SA','Arabia Saudita');
insert into pais values (seq_pais.nextval,'SB','Ilhas Salomao');
insert into pais values (seq_pais.nextval,'SC','Seicheles');
insert into pais values (seq_pais.nextval,'SD','Sudao');
insert into pais values (seq_pais.nextval,'SE','Suecia');
insert into pais values (seq_pais.nextval,'SG','Singapura');
insert into pais values (seq_pais.nextval,'SH','Santa Helena');
insert into pais values (seq_pais.nextval,'SI','Eslovenia');
insert into pais values (seq_pais.nextval,'SK','Eslovaquia');
insert into pais values (seq_pais.nextval,'SL','Serra Leoa');
insert into pais values (seq_pais.nextval,'SM','Sao Marino');
insert into pais values (seq_pais.nextval,'SN','Senegal');
insert into pais values (seq_pais.nextval,'SO','Somalia');
insert into pais values (seq_pais.nextval,'SR','Suriname');
insert into pais values (seq_pais.nextval,'ST','Sao Tome e Principe');
insert into pais values (seq_pais.nextval,'SV','El Salvador');
insert into pais values (seq_pais.nextval,'SY','Siria');
insert into pais values (seq_pais.nextval,'SZ','Suazilandia ');
insert into pais values (seq_pais.nextval,'TC','Ilhas Turks e Caicos');
insert into pais values (seq_pais.nextval,'TD','Chade');
insert into pais values (seq_pais.nextval,'TG','Togo');
insert into pais values (seq_pais.nextval,'TH','Tailandia');
insert into pais values (seq_pais.nextval,'TJ','Tajiquistao');
insert into pais values (seq_pais.nextval,'TK','Tokelau');
insert into pais values (seq_pais.nextval,'TM','Turcomenistao');
insert into pais values (seq_pais.nextval,'TN','Tunisia');
insert into pais values (seq_pais.nextval,'TO','Tonga');
insert into pais values (seq_pais.nextval,'TP','Timor Leste');
insert into pais values (seq_pais.nextval,'TR','Turquia');
insert into pais values (seq_pais.nextval,'TT','Trinidad e Tobago');
insert into pais values (seq_pais.nextval,'TV','Tuvalu');
insert into pais values (seq_pais.nextval,'TW','Taiwan');
insert into pais values (seq_pais.nextval,'TZ','Tanzania');
insert into pais values (seq_pais.nextval,'UA','Ucrania');
insert into pais values (seq_pais.nextval,'UG','Uganda');
insert into pais values (seq_pais.nextval,'US','Estados Unidos');
insert into pais values (seq_pais.nextval,'UY','Uruguai');
insert into pais values (seq_pais.nextval,'UZ','Uzbequistao');
insert into pais values (seq_pais.nextval,'VA','Vaticano');
insert into pais values (seq_pais.nextval,'VC','Sao Vicente e Granadinas');
insert into pais values (seq_pais.nextval,'VE','Venezuela');
insert into pais values (seq_pais.nextval,'VG','Ilhas Virgens Britanicas');
insert into pais values (seq_pais.nextval,'VI','Ilhas Virgens Americanas');
insert into pais values (seq_pais.nextval,'VN','Vietnam');
insert into pais values (seq_pais.nextval,'VU','Vanuatu');
insert into pais values (seq_pais.nextval,'WS','Samoa');
insert into pais values (seq_pais.nextval,'YE','Iemen');
insert into pais values (seq_pais.nextval,'YU','Iugoslavia');
insert into pais values (seq_pais.nextval,'ZA','Africa do Sul');
insert into pais values (seq_pais.nextval,'ZM','Zambia');
insert into pais values (seq_pais.nextval,'ZR','Zaire');
insert into pais values (seq_pais.nextval,'ZW','Zimbabue');
update pais set nome = upper(nome);
commit;