CREATE OR REPLACE VIEW PLANO_CONTAS AS
SELECT
  ID_CONTA_CONTABIL,
  CODIGO,
  NUMERO_CONTA,
  (LPAD(' ', (LEVEL * 2)-2) || NOME_REDUZIDO) NOME_REDUZIDO,
  NOME,
  TIPO_OPERACAO
FROM
  (
    SELECT
      CTB.ID_CONTA_CONTABIL,
      CTB.CODIGO,
      (
        GC.CODIGO || CASE WHEN CC.CODIGO IS NOT NULL THEN '.' ELSE '' END ||
        CC.CODIGO || CASE WHEN C.CODIGO IS NOT NULL THEN '.' ELSE '' END ||
        C.CODIGO || CASE WHEN SC.CODIGO IS NOT NULL THEN '.' ELSE '' END ||
        SC.CODIGO
      ) NUMERO_CONTA,
      NVL(SC.NOME, NVL(C.NOME, NVL(CC.NOME, GC.NOME))) NOME_REDUZIDO,
      SUBSTR(
        (
          GC.NOME || CASE WHEN CC.CODIGO IS NOT NULL THEN '/' ELSE '' END ||
          CC.NOME || CASE WHEN C.CODIGO IS NOT NULL THEN '/' ELSE '' END ||
          C.NOME || CASE WHEN SC.CODIGO IS NOT NULL THEN '/' ELSE '' END ||
          SC.NOME
        ),
        1,
        83
      ) NOME,
      (
        CASE WHEN CC.CODIGO IS NOT NULL THEN GC.CODIGO ELSE '' END || CASE WHEN C.CODIGO IS NOT NULL THEN '.' ELSE '' END ||
        CASE WHEN C.CODIGO IS NOT NULL THEN CC.CODIGO ELSE '' END || CASE WHEN SC.CODIGO IS NOT NULL THEN '.' ELSE '' END ||
        CASE WHEN SC.CODIGO IS NOT NULL THEN C.CODIGO ELSE '' END
      ) NUMERO_CONTA_SUPER,
      GC.TIPO_OPERACAO
    FROM
      SUB_CONTA SC,
      CONTA C,
      CENTRO_CUSTOS CC,
      GRUPO_CONTAS GC,
      CONTA_CONTABIL CTB
    WHERE
      GC.ID_GRUPO_CONTAS = CTB.ID_GRUPO_CONTAS AND
      CC.ID_CENTRO_CUSTOS(+) = CTB.ID_CENTRO_CUSTOS AND
      C.ID_CONTA(+) = CTB.ID_CONTA AND
      SC.ID_SUB_CONTA(+) = CTB.ID_SUB_CONTA
  )  
START WITH
  NUMERO_CONTA_SUPER IS NULL
CONNECT BY
  PRIOR NUMERO_CONTA = NUMERO_CONTA_SUPER

